import {
  Atom,
  Award,
  Beaker,
  Binary,
  Blocks,
  BookMarked,
  Bot,
  BotMessageSquare,
  CalendarCheck2,
  ClipboardCheck,
  CodeXml,
  Compass,
  Construction,
  GalleryHorizontalEnd,
  GitMerge,
  Handshake,
  HeartPulse,
  HousePlus,
  Languages,
  Layers3,
  Leaf,
  Lightbulb,
  Megaphone,
  MessageCircleHeart,
  MessagesSquare,
  MonitorCog,
  Music2,
  Orbit,
  PartyPopper,
  Presentation,
  RefreshCcwDot,
  Rocket,
  ScanSearch,
  School,
  Shield,
  ShieldCheck,
  Sigma,
  Sparkles,
  Trophy,
  UserRoundCheck,
  UsersRound,
} from "lucide-react";

type Props = {
  name: string;
  size?: number;
  className?: string;
};

const icons = {
  Atom,
  Award,
  Beaker,
  Binary,
  Blocks,
  BookMarked,
  BotMessageSquare,
  CalendarCheck2,
  ClipboardCheck,
  CodeXml,
  Compass,
  Construction,
  GalleryHorizontalEnd,
  GitMerge,
  Handshake,
  HeartPulse,
  HousePlus,
  Languages,
  Layers3,
  Leaf,
  Lightbulb,
  Megaphone,
  MessageCircleHeart,
  MessagesSquare,
  MonitorCog,
  Music2,
  Orbit,
  PartyPopper,
  Presentation,
  RefreshCcwDot,
  Robot: Bot,
  Rocket,
  ScanSearch,
  School,
  Shield,
  ShieldCheck,
  Sigma,
  Sparkles,
  Trophy,
  UserRoundCheck,
  UsersRound,
};

export function IconGlyph({ name, size = 20, className }: Props) {
  const Icon = (icons as Record<string, typeof Atom>)[name] ?? Sparkles;
  return <Icon size={size} className={className} aria-hidden />;
}
